/* gui_image.h — Qt6 stub
 * This stub provides the IMAGE_* enum and function declarations.
 */

enum {
  IMAGE_ANIMATE,
  IMAGE_ARROW,
  IMAGE_AXES,
  IMAGE_CANVAS_SINGLE,
  IMAGE_CANVAS_CREATE,
  IMAGE_CANVAS_DELETE,
  IMAGE_CAMERA,
  IMAGE_COMPASS,
  IMAGE_CROSS,
  IMAGE_DIFFRACTION,
  IMAGE_DISK,
  IMAGE_ELEMENT,
  IMAGE_FOLDER,
  IMAGE_ISOSURFACE,
  IMAGE_MEASURE,
  IMAGE_PERIODIC,
  IMAGE_PALETTE,
  IMAGE_PLOTS,
  IMAGE_TO_EPS,
  IMAGE_PLUS,
  IMAGE_SELECT_ALL,
  IMAGE_SURFACE,
  IMAGE_TOOLS,
  IMAGE_TRACK,
  IMAGE_XVIEW,
  IMAGE_YVIEW,
  IMAGE_ZVIEW,
  IMAGE_AVIEW,
  IMAGE_BVIEW,
  IMAGE_CVIEW,
  IMAGE_XROTATE,
  IMAGE_YROTATE,
  IMAGE_ZROTATE,
  IMAGE_LAST
};

void image_table_init(void);
gpointer image_table_lookup(const gchar *);
